spring:
  profiles:
    include: secret
  config:import:optional:file: .env[.properties]
  application:
    name: minilog-graphql
  datasource:
    url: jdbc:mysql://localhost:3307/minilog_db
    username: minilog_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    graphiql:
      enabled: true
      path: graphiql